//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scorelink.MO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScorelinkEntities1 : DbContext
    {
        public ScorelinkEntities1()
            : base("name=ScorelinkEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccTitleDict> AccTitleDict { get; set; }
        public virtual DbSet<DocumentArea> DocumentArea { get; set; }
        public virtual DbSet<DocumentDetail> DocumentDetail { get; set; }
        public virtual DbSet<DocumentInfoes> DocumentInfoes { get; set; }
        public virtual DbSet<OCRResult> OCRResult { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
